# Generated by Django 6.1.1 on 2026-10-02 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallermami', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_asignados', to='tallermami.trabajador', verbose_name='Trabajador asignado'),
        ),
    ]
