# Generated by Django 6.1.1 on 2026-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallermami', '0002_turno_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='trabajos',
            field=models.ManyToManyField(blank=True, related_name='trabajadores', to='tallermami.trabajo', verbose_name='Trabajos asignados'),
        ),
    ]
