# Generated by Django 6.1.1 on 2026-10-08 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallermami', '0003_trabajador_trabajos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponible', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('turno_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_recibidas', to='tallermami.turno')),
            ],
            options={
                'verbose_name': 'Oferta de turno anterior',
                'verbose_name_plural': 'Ofertas de turnos anteriores',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
